### ISSUE TITLE
LINK : fatal error LNK1181

### ISSUE THREAD

**Issue by phamvanthanh** [gluonhq/substrate#682] opened 2020-06-30 16:33 UTC
Hi,
I tried GraalVM 11 CE 20.2.0-dev-20200630_0216 on windows and failed at LINK phase with error: 
` LINK : fatal error LNK1181: cannot open input file 'j2pkcs11.lib'`

**Comment by tiainen** [comment] 2020-06-30 16:46
Duplicate of #679 .

**Closed by tiainen** 2020-06-30 16:46 UTC
